<?php

namespace Container5x4oVE6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EfEAx1yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EfEAx1y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EfEAx1y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quizzHistoryRepository' => ['privates', 'App\\Repository\\QuizzHistoryRepository', 'getQuizzHistoryRepositoryService', true],
        ], [
            'quizzHistoryRepository' => 'App\\Repository\\QuizzHistoryRepository',
        ]);
    }
}
