<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2F5LvL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2F5LvL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV2F5LvL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV2F5LvL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV2F5LvL\App_KernelDevDebugContainer([
    'container.build_hash' => 'V2F5LvL',
    'container.build_id' => 'ba746047',
    'container.build_time' => 1677222811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2F5LvL');
